import { Dimensions, StyleSheet } from "react-native";

const { width: SCREEN_WIDTH } = Dimensions.get("window");
const BOARD_SIZE = Math.min(SCREEN_WIDTH - 32, 360);
const SQUARE_SIZE = BOARD_SIZE / 8;


export const styles = StyleSheet.create({
    screen: {
        flex: 1,
        backgroundColor: "#0B1020",
    },
    modeSelectContent: {
        alignItems: "center",
        padding: 20,
        paddingBottom: 40,
    },
    hero: {
        alignItems: "center",
        marginTop: 20,
        marginBottom: 24,
    },
    heroBadge: {
        color: "#C084FC",
        fontSize: 12,
        fontWeight: "900",
        letterSpacing: 2,
        marginBottom: 4,
    },
    heroTitle: {
        color: "#FFFFFF",
        fontSize: 36,
        fontWeight: "900",
        letterSpacing: 3,
    },
    heroSubtitle: {
        color: "#8E99B0",
        fontSize: 14,
        marginTop: 6,
        textAlign: "center",
    },
    modeCard: {
        width: "100%",
        maxWidth: 340,
        backgroundColor: "#151C2E",
        borderWidth: 1.5,
        borderColor: "#A855F744",
        borderRadius: 18,
        padding: 18,
        marginBottom: 18,
    },
    computerCardBorder: {
        borderColor: "#00E5FF44",
    },
    modeHeader: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
    },
    modeIcon: {
        fontSize: 32,
    },
    modeTagContainer: {
        backgroundColor: "#A855F722",
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 8,
    },
    modeTagText: {
        color: "#C084FC",
        fontSize: 11,
        fontWeight: "900",
        letterSpacing: 1,
    },
    computerTagBg: {
        backgroundColor: "#00E5FF22",
    },
    computerTagText: {
        color: "#00E5FF",
        fontSize: 11,
        fontWeight: "900",
        letterSpacing: 1,
    },
    modeCardTitle: {
        color: "#FFFFFF",
        fontSize: 22,
        fontWeight: "900",
        marginTop: 12,
    },
    modeDesc: {
        color: "#9AA4B8",
        fontSize: 13,
        lineHeight: 19,
        marginTop: 6,
    },
    modeFooter: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginTop: 16,
        paddingTop: 12,
        borderTopWidth: 1,
        borderTopColor: "#202A3E",
    },
    modeFeatures: {
        color: "#6D7992",
        fontSize: 11,
        flex: 1,
    },
    modePlayBadge: {
        backgroundColor: "#A855F7",
        paddingHorizontal: 14,
        paddingVertical: 8,
        borderRadius: 10,
    },
    modePlayText: {
        color: "#18062B",
        fontWeight: "900",
        fontSize: 12,
        letterSpacing: 1,
    },
    computerPlayBadge: {
        backgroundColor: "#00E5FF",
    },
    computerPlayText: {
        color: "#002733",
        fontWeight: "900",
        fontSize: 12,
        letterSpacing: 1,
    },
    backHomeBtn: {
        marginTop: 12,
        paddingVertical: 12,
        paddingHorizontal: 20,
        borderRadius: 12,
        backgroundColor: "#151C2E",
        borderWidth: 1,
        borderColor: "#253046",
    },
    backHomeBtnText: {
        color: "#8E99B0",
        fontSize: 12,
        fontWeight: "800",
        letterSpacing: 1,
    },
    container: {
        alignItems: "center",
        padding: 16,
        paddingBottom: 48,
    },
    navBar: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        width: "100%",
        marginBottom: 12,
    },
    navButton: {
        backgroundColor: "#151C2E",
        borderWidth: 1,
        borderColor: "#253046",
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 10,
    },
    navButtonText: {
        color: "#8E99B0",
        fontWeight: "800",
        fontSize: 12,
        letterSpacing: 1,
    },
    titleContainer: {
        flexDirection: "row",
        alignItems: "center",
    },
    titleIcon: {
        fontSize: 20,
        marginRight: 6,
    },
    titleText: {
        color: "#FFFFFF",
        fontSize: 18,
        fontWeight: "900",
        letterSpacing: 2,
    },
    flipButton: {
        backgroundColor: "#A855F722",
        borderWidth: 1,
        borderColor: "#A855F744",
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 10,
    },
    flipButtonText: {
        color: "#C084FC",
        fontWeight: "800",
        fontSize: 12,
        letterSpacing: 1,
    },
    playerCard: {
        width: BOARD_SIZE + 24,
        backgroundColor: "#151C2E",
        borderWidth: 1.5,
        borderRadius: 14,
        padding: 12,
        marginVertical: 6,
    },
    whitePlayerBorder: {
        borderColor: "#49D17D44",
    },
    blackPlayerBorder: {
        borderColor: "#FFB74D44",
    },
    activePlayerCardGlow: {
        borderColor: "#A855F7",
        backgroundColor: "#191834",
    },
    playerInfoRow: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
    },
    playerNameGroup: {
        flexDirection: "row",
        alignItems: "center",
    },
    playerAvatar: {
        width: 32,
        height: 32,
        borderRadius: 16,
        justifyContent: "center",
        alignItems: "center",
        marginRight: 10,
    },
    whiteAvatar: {
        backgroundColor: "#E8C59E",
    },
    blackAvatar: {
        backgroundColor: "#1E293B",
        borderWidth: 1,
        borderColor: "#475569",
    },
    avatarSymbol: {
        fontSize: 18,
        color: "#0B1020",
    },
    playerName: {
        color: "#FFFFFF",
        fontSize: 14,
        fontWeight: "900",
        letterSpacing: 1,
    },
    playerSubtext: {
        color: "#8E99B0",
        fontSize: 10,
        fontWeight: "700",
        marginTop: 2,
    },
    advantageBadge: {
        backgroundColor: "#49D17D22",
        paddingHorizontal: 8,
        paddingVertical: 3,
        borderRadius: 6,
        borderWidth: 1,
        borderColor: "#49D17D55",
    },
    advantageText: {
        color: "#49D17D",
        fontSize: 12,
        fontWeight: "900",
    },
    capturedRow: {
        flexDirection: "row",
        alignItems: "center",
        marginTop: 8,
        paddingTop: 6,
        borderTopWidth: 1,
        borderTopColor: "#202A3E",
    },
    capturedLabel: {
        color: "#6D7992",
        fontSize: 11,
        marginRight: 6,
    },
    noneCaptured: {
        color: "#475569",
        fontSize: 11,
        fontStyle: "italic",
    },
    capturedPiecesList: {
        flexDirection: "row",
        flexWrap: "wrap",
        alignItems: "center",
    },
    capturedPieceSymbol: {
        fontSize: 16,
        marginHorizontal: 1,
    },
    capturedWhitePiece: {
        color: "#E8C59E",
    },
    capturedBlackPiece: {
        color: "#CBD5E1",
    },
    checkAlertBanner: {
        backgroundColor: "#EF444422",
        borderWidth: 1,
        borderColor: "#EF444488",
        borderRadius: 8,
        paddingVertical: 6,
        paddingHorizontal: 16,
        marginVertical: 4,
        width: BOARD_SIZE + 24,
        alignItems: "center",
    },
    checkAlertText: {
        color: "#F87171",
        fontSize: 12,
        fontWeight: "900",
        letterSpacing: 1,
    },
    boardWrapper: {
        alignItems: "center",
        marginVertical: 6,
    },
    fileLabelsRow: {
        flexDirection: "row",
        width: BOARD_SIZE,
        paddingLeft: 18,
        justifyContent: "space-around",
        marginBottom: 4,
    },
    boardWithRanks: {
        flexDirection: "row",
        alignItems: "center",
    },
    rankLabelsColumn: {
        height: BOARD_SIZE,
        justifyContent: "space-around",
        marginRight: 6,
        width: 12,
        alignItems: "center",
    },
    coordinateLabel: {
        color: "#64748B",
        fontSize: 11,
        fontWeight: "800",
    },
    board: {
        width: BOARD_SIZE,
        height: BOARD_SIZE,
        borderRadius: 12,
        overflow: "hidden",
        borderWidth: 3,
        borderColor: "#253046",
    },
    row: {
        flexDirection: "row",
        height: SQUARE_SIZE,
    },
    square: {
        width: SQUARE_SIZE,
        height: SQUARE_SIZE,
        justifyContent: "center",
        alignItems: "center",
    },
    lightSquare: {
        backgroundColor: "#EEEED2",
    },
    darkSquare: {
        backgroundColor: "#769656",
    },
    selectedSquare: {
        backgroundColor: "#FACC15",
    },
    lastMoveSquare: {
        backgroundColor: "#BBDB44",
    },
    checkedKingSquare: {
        backgroundColor: "#EF4444",
    },
    validMoveDot: {
        width: 14,
        height: 14,
        borderRadius: 7,
        backgroundColor: "rgba(0, 0, 0, 0.28)",
    },
    captureRing: {
        position: "absolute",
        width: SQUARE_SIZE - 4,
        height: SQUARE_SIZE - 4,
        borderRadius: (SQUARE_SIZE - 4) / 2,
        borderWidth: 3,
        borderColor: "rgba(220, 38, 38, 0.75)",
    },
    pieceText: {
        fontSize: SQUARE_SIZE * 0.78,
        textAlign: "center",
        includeFontPadding: false,
    },
    whitePiece: {
        color: "#E8C59E",
        textShadowColor: "rgba(35, 18, 5, 0.95)",
        textShadowOffset: { width: 0, height: 1.5 },
        textShadowRadius: 3,
    },
    blackPiece: {
        color: "#18181B",
        textShadowColor: "rgba(255, 255, 255, 0.4)",
        textShadowOffset: { width: 0, height: 1 },
        textShadowRadius: 2,
    },
    controlsBar: {
        flexDirection: "row",
        justifyContent: "space-between",
        width: BOARD_SIZE + 24,
        marginTop: 12,
    },
    actionButton: {
        flex: 1,
        backgroundColor: "#151C2E",
        borderWidth: 1,
        borderColor: "#253046",
        paddingVertical: 10,
        borderRadius: 10,
        alignItems: "center",
        marginHorizontal: 4,
    },
    disabledButton: {
        opacity: 0.4,
    },
    actionButtonText: {
        color: "#94A3B8",
        fontSize: 11,
        fontWeight: "900",
        letterSpacing: 1,
    },
    resignText: {
        color: "#F87171",
    },
    resetText: {
        color: "#FBBF24",
    },
    infoCard: {
        marginTop: 10,
        paddingVertical: 6,
        paddingHorizontal: 16,
        borderRadius: 8,
        backgroundColor: "#151C2E88",
    },
    infoText: {
        color: "#64748B",
        fontSize: 12,
        fontWeight: "700",
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: "rgba(5, 8, 16, 0.88)",
        justifyContent: "center",
        alignItems: "center",
        padding: 24,
    },
    modalCard: {
        width: "100%",
        maxWidth: 340,
        backgroundColor: "#151C2E",
        borderWidth: 2,
        borderColor: "#A855F7",
        borderRadius: 20,
        padding: 24,
        alignItems: "center",
    },
    modalTrophy: {
        fontSize: 36,
        marginBottom: 8,
    },
    modalTitle: {
        color: "#FFFFFF",
        fontSize: 26,
        fontWeight: "900",
        letterSpacing: 2,
    },
    modalReason: {
        color: "#A855F7",
        fontSize: 14,
        fontWeight: "700",
        textAlign: "center",
        marginTop: 8,
        marginBottom: 24,
        lineHeight: 20,
    },
    modalPrimaryBtn: {
        width: "100%",
        paddingVertical: 14,
        borderRadius: 12,
        alignItems: "center",
        marginBottom: 10,
    },
    rematchBtn: {
        backgroundColor: "#A855F7",
    },
    rematchBtnText: {
        color: "#18062B",
        fontSize: 14,
        fontWeight: "900",
        letterSpacing: 1.5,
    },
    modalSecondaryBtn: {
        width: "100%",
        paddingVertical: 12,
        borderRadius: 12,
        alignItems: "center",
        backgroundColor: "#1F293D",
    },
    modalSecondaryText: {
        color: "#94A3B8",
        fontSize: 13,
        fontWeight: "800",
        letterSpacing: 1,
    },
});