import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  // Main Container & Table
  container: {
    flex: 1,
    backgroundColor: "#06130D",
  },
  tableFelt: {
    flex: 1,
    backgroundColor: "#0B291B",
    borderRadius: 24,
    margin: 8,
    borderWidth: 3,
    borderColor: "#D4AF37", // Casino Gold Border
    overflow: "hidden",
    justifyContent: "space-between",
  },

  // Header Bar
  headerBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 14,
    paddingVertical: 10,
    backgroundColor: "rgba(3, 15, 9, 0.75)",
    borderBottomWidth: 1,
    borderBottomColor: "rgba(212, 175, 55, 0.3)",
  },
  headerLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  backButton: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: "rgba(255, 255, 255, 0.12)",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.2)",
  },
  backButtonText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "700",
  },
  gameTitleGujarati: {
    color: "#FFD700",
    fontSize: 16,
    fontWeight: "900",
    letterSpacing: 0.5,
  },
  gameTitleEng: {
    color: "#A7F3D0",
    fontSize: 12,
    fontWeight: "600",
  },
  headerRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  roundBadge: {
    backgroundColor: "rgba(212, 175, 55, 0.2)",
    borderWidth: 1,
    borderColor: "#D4AF37",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  roundBadgeText: {
    color: "#FFDF79",
    fontSize: 12,
    fontWeight: "800",
  },

  // Opponents Area
  opponentsContainer: {
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    paddingHorizontal: 8,
    paddingTop: 6,
  },
  seatBox: {
    alignItems: "center",
    padding: 6,
    borderRadius: 14,
    backgroundColor: "rgba(0, 0, 0, 0.4)",
    borderWidth: 1.5,
    borderColor: "transparent",
    minWidth: 84,
  },
  activeSeatBox: {
    borderColor: "#00E5FF",
    backgroundColor: "rgba(0, 229, 255, 0.15)",
    shadowColor: "#00E5FF",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 8,
    elevation: 6,
  },
  seatAvatar: {
    fontSize: 22,
    marginBottom: 2,
  },
  seatName: {
    color: "#E2E8F0",
    fontSize: 11,
    fontWeight: "700",
    maxWidth: 80,
    textAlign: "center",
  },
  seatStats: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginTop: 2,
  },
  seatCardCountBadge: {
    backgroundColor: "rgba(255, 255, 255, 0.15)",
    paddingHorizontal: 5,
    paddingVertical: 1,
    borderRadius: 6,
  },
  seatCardCountText: {
    color: "#FFFFFF",
    fontSize: 10,
    fontWeight: "700",
  },
  seatTensBadge: {
    backgroundColor: "rgba(239, 68, 68, 0.25)",
    borderWidth: 1,
    borderColor: "#EF4444",
    paddingHorizontal: 5,
    paddingVertical: 1,
    borderRadius: 6,
  },
  seatTensText: {
    color: "#FCA5A5",
    fontSize: 10,
    fontWeight: "800",
  },

  // Center Dhagla Board
  centerBoard: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 6,
  },
  dhaglaFeltCircle: {
    width: 240,
    height: 180,
    borderRadius: 90,
    backgroundColor: "rgba(3, 30, 16, 0.7)",
    borderWidth: 2,
    borderColor: "rgba(212, 175, 55, 0.4)",
    justifyContent: "center",
    alignItems: "center",
    position: "relative",
  },
  dhaglaLabel: {
    position: "absolute",
    top: 10,
    color: "rgba(212, 175, 55, 0.6)",
    fontSize: 12,
    fontWeight: "900",
    letterSpacing: 2,
  },
  centerTrickCardsRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    zIndex: 10,
  },
  streakBanner: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(245, 158, 11, 0.95)",
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 16,
    marginTop: 8,
    shadowColor: "#F59E0B",
    shadowOpacity: 0.6,
    shadowRadius: 6,
    elevation: 4,
  },
  streakBannerText: {
    color: "#000000",
    fontSize: 12,
    fontWeight: "900",
  },
  leadSuitTag: {
    position: "absolute",
    bottom: 8,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.65)",
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.2)",
  },
  leadSuitText: {
    color: "#F1F5F9",
    fontSize: 11,
    fontWeight: "700",
  },

  // Turn Action Indicator Banner
  turnBanner: {
    backgroundColor: "rgba(16, 185, 129, 0.9)",
    paddingVertical: 6,
    paddingHorizontal: 16,
    borderRadius: 20,
    alignSelf: "center",
    marginBottom: 6,
    shadowColor: "#10B981",
    shadowOpacity: 0.5,
    shadowRadius: 8,
    elevation: 4,
  },
  turnBannerText: {
    color: "#FFFFFF",
    fontSize: 13,
    fontWeight: "900",
    textAlign: "center",
  },

  // Bottom Hand Section
  bottomSection: {
    backgroundColor: "rgba(2, 18, 10, 0.88)",
    borderTopWidth: 2,
    borderTopColor: "rgba(212, 175, 55, 0.4)",
    paddingTop: 8,
    paddingBottom: 12,
  },
  playerStatusBar: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 16,
    marginBottom: 6,
  },
  playerStatsLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  playerAvatar: {
    fontSize: 18,
  },
  playerName: {
    color: "#FFDF79",
    fontSize: 14,
    fontWeight: "800",
  },
  playerStatsRight: {
    flexDirection: "row",
    gap: 8,
  },
  tensCollectedBadge: {
    backgroundColor: "#DC2626",
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
  },
  tensCollectedText: {
    color: "#FFFFFF",
    fontSize: 11,
    fontWeight: "900",
  },

  // Hand Scroll Area
  handScrollView: {
    paddingHorizontal: 12,
    paddingVertical: 4,
  },
  handCardsContainer: {
    flexDirection: "row",
    alignItems: "flex-end",
    gap: -14, // Fanned overlap
    paddingRight: 30,
  },

  // Playing Card Component Styles
  cardWrapper: {
    borderRadius: 8,
    backgroundColor: "#FFFFFF",
    borderWidth: 1.5,
    borderColor: "#CBD5E1",
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.35,
    shadowRadius: 3,
    elevation: 4,
    overflow: "hidden",
  },
  cardSelected: {
    borderColor: "#00E5FF",
    borderWidth: 2.5,
    transform: [{ translateY: -12 }],
    shadowColor: "#00E5FF",
    shadowOpacity: 0.9,
    shadowRadius: 8,
    elevation: 8,
  },
  cardDisabled: {
    opacity: 0.45,
  },
  bigCenterCardShadow: {
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.6,
    shadowRadius: 10,
    elevation: 10,
    borderWidth: 2,
    borderColor: "#F1F5F9",
  },
  cardInner: {
    flex: 1,
    justifyContent: "space-between",
    padding: 3,
  },
  cardCornerTop: {
    alignItems: "flex-start",
  },
  cardCornerBottom: {
    alignItems: "flex-end",
    transform: [{ rotate: "180deg" }],
  },
  cardRankText: {
    fontSize: 13,
    fontWeight: "900",
    lineHeight: 14,
  },
  cardSuitSmall: {
    fontSize: 10,
    lineHeight: 11,
  },
  cardCenterSymbol: {
    alignSelf: "center",
    fontSize: 20,
    fontWeight: "900",
  },
  cardBack: {
    backgroundColor: "#991B1B",
    borderWidth: 2,
    borderColor: "#FCD34D",
    justifyContent: "center",
    alignItems: "center",
  },
  cardBackPattern: {
    width: "80%",
    height: "80%",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.4)",
    borderRadius: 4,
    justifyContent: "center",
    alignItems: "center",
  },
  cardBackIcon: {
    fontSize: 14,
  },

  // Mode Selection Screen
  modeScreen: {
    flex: 1,
    backgroundColor: "#08150F",
    paddingHorizontal: 16,
    paddingTop: 12,
  },
  modeHeader: {
    alignItems: "center",
    marginVertical: 14,
  },
  modeMainTitle: {
    color: "#FFD700",
    fontSize: 28,
    fontWeight: "900",
    letterSpacing: 1,
  },
  modeSubTitle: {
    color: "#34D399",
    fontSize: 18,
    fontWeight: "800",
    marginTop: 2,
  },
  modeDesc: {
    color: "#94A3B8",
    fontSize: 12,
    textAlign: "center",
    marginTop: 6,
    paddingHorizontal: 20,
  },
  playerCountSelector: {
    flexDirection: "row",
    justifyContent: "center",
    gap: 12,
    marginVertical: 12,
  },
  playerCountBtn: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 12,
    backgroundColor: "rgba(255, 255, 255, 0.08)",
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.2)",
  },
  playerCountBtnActive: {
    backgroundColor: "#059669",
    borderColor: "#34D399",
  },
  playerCountText: {
    color: "#E2E8F0",
    fontSize: 14,
    fontWeight: "800",
  },
  playerCountTextActive: {
    color: "#FFFFFF",
  },
  modeCardsContainer: {
    gap: 12,
    paddingBottom: 20,
  },
  modeCard: {
    backgroundColor: "rgba(15, 42, 30, 0.85)",
    borderRadius: 16,
    padding: 14,
    borderWidth: 1.5,
    borderColor: "rgba(52, 211, 153, 0.3)",
  },
  modeCardHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 6,
  },
  modeCardTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  modeCardIcon: {
    fontSize: 24,
  },
  modeCardTitle: {
    color: "#FFFFFF",
    fontSize: 17,
    fontWeight: "900",
  },
  modeTagBadge: {
    backgroundColor: "rgba(52, 211, 153, 0.2)",
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 8,
  },
  modeTagText: {
    color: "#34D399",
    fontSize: 11,
    fontWeight: "800",
  },
  modeCardDesc: {
    color: "#94A3B8",
    fontSize: 12,
    lineHeight: 17,
    marginBottom: 10,
  },
  modeStartButton: {
    backgroundColor: "#10B981",
    paddingVertical: 10,
    borderRadius: 10,
    alignItems: "center",
  },
  modeStartButtonText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "900",
    letterSpacing: 0.5,
  },
  rulesBox: {
    backgroundColor: "rgba(0, 0, 0, 0.4)",
    borderRadius: 14,
    padding: 12,
    borderWidth: 1,
    borderColor: "rgba(212, 175, 55, 0.3)",
    marginTop: 4,
    marginBottom: 24,
  },
  rulesTitle: {
    color: "#FFDF79",
    fontSize: 14,
    fontWeight: "900",
    marginBottom: 6,
  },
  ruleLine: {
    color: "#CBD5E1",
    fontSize: 12,
    lineHeight: 18,
    marginVertical: 2,
  },

  // Lobby Screen
  lobbyContainer: {
    flex: 1,
    backgroundColor: "#08150F",
    padding: 16,
  },
  lobbyHeader: {
    alignItems: "center",
    marginVertical: 12,
  },
  lobbyTitle: {
    color: "#FFD700",
    fontSize: 24,
    fontWeight: "900",
  },
  lobbySub: {
    color: "#A7F3D0",
    fontSize: 13,
    marginTop: 2,
  },
  ipCard: {
    backgroundColor: "rgba(15, 42, 30, 0.9)",
    borderRadius: 16,
    padding: 16,
    borderWidth: 1.5,
    borderColor: "#10B981",
    marginVertical: 12,
    alignItems: "center",
  },
  ipLabel: {
    color: "#94A3B8",
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
  },
  ipValue: {
    color: "#34D399",
    fontSize: 26,
    fontWeight: "900",
    letterSpacing: 1,
    marginVertical: 4,
  },
  ipHint: {
    color: "#CBD5E1",
    fontSize: 11,
    textAlign: "center",
  },
  slotsCard: {
    backgroundColor: "rgba(0, 0, 0, 0.35)",
    borderRadius: 16,
    padding: 14,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
    marginVertical: 8,
  },
  slotsTitle: {
    color: "#F1F5F9",
    fontSize: 14,
    fontWeight: "800",
    marginBottom: 10,
  },
  slotRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.08)",
  },
  slotLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  slotAvatar: {
    fontSize: 20,
  },
  slotName: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "700",
  },
  slotStatusBadge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
  },
  slotStatusReady: {
    backgroundColor: "rgba(16, 185, 129, 0.2)",
    borderWidth: 1,
    borderColor: "#10B981",
  },
  slotStatusWaiting: {
    backgroundColor: "rgba(245, 158, 11, 0.15)",
    borderWidth: 1,
    borderColor: "#F59E0B",
  },
  slotStatusText: {
    fontSize: 11,
    fontWeight: "800",
  },
  joinInputRow: {
    flexDirection: "row",
    gap: 8,
    marginVertical: 12,
  },
  ipInput: {
    flex: 1,
    backgroundColor: "rgba(255, 255, 255, 0.08)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.2)",
    borderRadius: 10,
    paddingHorizontal: 12,
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "700",
  },
  connectBtn: {
    backgroundColor: "#059669",
    paddingHorizontal: 16,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
  },
  connectBtnText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "800",
  },
});
