import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    scrollScreen: {
        flex: 1,
        backgroundColor: "#0B1020",
    },
    content: {
        padding: 16,
        paddingBottom: 36,
        alignItems: "center",
    },
    hero: {
        width: "100%",
        maxWidth: 380,
        alignItems: "center",
        marginTop: 8,
        marginBottom: 14,
    },
    badge: {
        color: "#FF704D",
        fontSize: 12,
        fontWeight: "900",
        letterSpacing: 2,
        marginBottom: 4,
    },
    title: {
        color: "#FFFFFF",
        fontSize: 32,
        fontWeight: "900",
        letterSpacing: 2,
    },
    subtitle: {
        color: "#8E99B0",
        fontSize: 13,
        marginTop: 4,
        textAlign: "center",
        lineHeight: 18,
    },
    statsRow: {
        width: "100%",
        maxWidth: 380,
        flexDirection: "row",
        justifyContent: "space-between",
        marginBottom: 14,
    },
    statCard: {
        flex: 1,
        backgroundColor: "#151C2E",
        borderWidth: 1,
        borderColor: "#253046",
        borderRadius: 14,
        paddingVertical: 10,
        paddingHorizontal: 8,
        alignItems: "center",
        marginHorizontal: 3,
    },
    statLabel: {
        color: "#8E99B0",
        fontSize: 10,
        fontWeight: "900",
        letterSpacing: 1,
        marginBottom: 2,
    },
    statValue: {
        color: "#FFFFFF",
        fontSize: 18,
        fontWeight: "900",
    },
    boardSection: {
        width: "100%",
        maxWidth: 380,
        alignItems: "center",
        marginBottom: 14,
    },
    boardHeader: {
        width: "100%",
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "flex-start",
        marginBottom: 10,
        paddingHorizontal: 6,
        gap: 12,
    },
    sectionLabel: {
        color: "#D5DBE8",
        fontSize: 11,
        fontWeight: "900",
        letterSpacing: 1,
        marginBottom: 4,
    },
    sectionHint: {
        color: "#8E99B0",
        fontSize: 11,
        lineHeight: 15,
        maxWidth: 200,
    },
    nextPieceCard: {
        backgroundColor: "#151C2E",
        borderWidth: 1,
        borderColor: "#253046",
        borderRadius: 12,
        padding: 8,
        alignItems: "center",
    },
    previewGrid: {
        width: 56,
        height: 56,
        justifyContent: "center",
        alignItems: "center",
    },
    previewRow: {
        flexDirection: "row",
    },
    previewCell: {
        width: 12,
        height: 12,
        margin: 1,
        borderRadius: 2,
        backgroundColor: "#1F2940",
    },
    board: {
        alignSelf: "center",
        backgroundColor: "#0D1322",
        borderRadius: 14,
        borderWidth: 2,
        borderColor: "#253046",
        overflow: "hidden",
    },
    boardRow: {
        flexDirection: "row",
    },
    cell: {
        borderWidth: 0.5,
        borderColor: "#192238",
        backgroundColor: "#11182A",
    },
    controlPad: {
        width: "100%",
        maxWidth: 340,
        marginBottom: 8,
    },
    controlRow: {
        flexDirection: "row",
        justifyContent: "center",
        gap: 10,
        marginBottom: 10,
    },
    controlButton: {
        minWidth: 84,
        backgroundColor: "#151C2E",
        borderWidth: 1,
        borderColor: "#253046",
        borderRadius: 12,
        paddingVertical: 12,
        paddingHorizontal: 12,
        alignItems: "center",
        justifyContent: "center",
    },
    controlButtonText: {
        color: "#FFFFFF",
        fontSize: 18,
        fontWeight: "900",
    },
    hardDropButton: {
        backgroundColor: "#FF704D",
        borderColor: "#FF704D",
        flex: 1.5,
    },
    hardDropButtonText: {
        color: "#2A1208",
        fontSize: 13,
        fontWeight: "900",
        letterSpacing: 1,
    },
    statusText: {
        width: "100%",
        maxWidth: 340,
        color: "#9AA4B8",
        fontSize: 11,
        textAlign: "center",
        lineHeight: 16,
        marginTop: 4,
        marginBottom: 12,
    },
    primaryButton: {
        width: "100%",
        maxWidth: 340,
        backgroundColor: "#FF704D",
        borderRadius: 12,
        paddingVertical: 14,
        alignItems: "center",
        marginBottom: 10,
    },
    primaryButtonText: {
        color: "#2A1208",
        fontSize: 13,
        fontWeight: "900",
        letterSpacing: 1,
    },
    secondaryButton: {
        width: "100%",
        maxWidth: 340,
        borderWidth: 1,
        borderColor: "#253046",
        borderRadius: 12,
        paddingVertical: 12,
        alignItems: "center",
    },
    secondaryButtonText: {
        color: "#D5DBE8",
        fontSize: 12,
        fontWeight: "900",
        letterSpacing: 1,
    },
    resultCard: {
        width: "100%",
        maxWidth: 340,
        backgroundColor: "#151C2E",
        borderWidth: 1,
        borderColor: "#253046",
        borderRadius: 16,
        padding: 16,
        marginBottom: 16,
    },
    resultCardLabel: {
        color: "#8E99B0",
        fontSize: 10,
        fontWeight: "900",
        letterSpacing: 1,
        marginBottom: 6,
    },
    resultScore: {
        color: "#FFFFFF",
        fontSize: 36,
        fontWeight: "900",
        marginBottom: 12,
    },
    resultStatsRow: {
        flexDirection: "row",
        gap: 10,
        marginBottom: 14,
    },
    resultStat: {
        flex: 1,
        backgroundColor: "#11182A",
        borderRadius: 12,
        paddingVertical: 10,
        alignItems: "center",
    },
    resultStatLabel: {
        color: "#8E99B0",
        fontSize: 10,
        fontWeight: "900",
        letterSpacing: 1,
        marginBottom: 2,
    },
    resultStatValue: {
        color: "#FFFFFF",
        fontSize: 18,
        fontWeight: "900",
    },
    resultPreviewWrap: {
        alignItems: "center",
        marginTop: 8,
    },
    resultPreviewLabel: {
        color: "#8E99B0",
        fontSize: 10,
        fontWeight: "900",
        letterSpacing: 1,
        marginBottom: 8,
    },
});