import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    scrollScreen: {
        flex: 1,
        backgroundColor: "#0B1020",
    },
    content: {
        padding: 20,
        paddingBottom: 36,
        alignItems: "center",
    },
    hero: {
        width: "100%",
        marginTop: 16,
        marginBottom: 18,
        alignItems: "center",
    },
    badge: {
        color: "#FFB74D",
        fontSize: 12,
        fontWeight: "900",
        letterSpacing: 2,
        marginBottom: 6,
    },
    title: {
        color: "#FFFFFF",
        fontSize: 34,
        fontWeight: "900",
        letterSpacing: 2,
    },
    titleSmall: {
        color: "#FFFFFF",
        fontSize: 28,
        fontWeight: "900",
        letterSpacing: 1.5,
    },
    subtitle: {
        color: "#8E99B0",
        fontSize: 14,
        marginTop: 8,
        textAlign: "center",
        lineHeight: 20,
    },
    modeCard: {
        width: "100%",
        maxWidth: 360,
        backgroundColor: "#151C2E",
        borderRadius: 18,
        borderWidth: 1,
        borderColor: "#FFB74D33",
        padding: 18,
        marginBottom: 16,
    },
    computerCard: {
        borderColor: "#49D17D33",
    },
    modeIcon: {
        fontSize: 32,
        marginBottom: 8,
    },
    modeTitle: {
        color: "#FFFFFF",
        fontSize: 20,
        fontWeight: "900",
        letterSpacing: 1,
    },
    modeDesc: {
        color: "#9AA4B8",
        fontSize: 13,
        lineHeight: 19,
        marginTop: 8,
    },
    modePill: {
        marginTop: 14,
        color: "#FFB74D",
        fontSize: 11,
        fontWeight: "900",
        letterSpacing: 1,
    },
    computerPill: {
        color: "#49D17D",
    },
    backButton: {
        width: "100%",
        maxWidth: 360,
        borderWidth: 1,
        borderColor: "#253046",
        borderRadius: 14,
        paddingVertical: 14,
        alignItems: "center",
        marginTop: 4,
    },
    backButtonText: {
        color: "#D5DBE8",
        fontSize: 12,
        fontWeight: "900",
        letterSpacing: 1,
    },
    gameHeader: {
        width: "100%",
        maxWidth: 360,
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginTop: 12,
        marginBottom: 16,
    },
    turnChip: {
        backgroundColor: "#151C2E",
        borderWidth: 1,
        borderColor: "#253046",
        borderRadius: 14,
        paddingHorizontal: 14,
        paddingVertical: 10,
        minWidth: 86,
        alignItems: "center",
    },
    turnChipLabel: {
        color: "#8E99B0",
        fontSize: 10,
        fontWeight: "900",
        letterSpacing: 1,
        marginBottom: 2,
    },
    turnChipValue: {
        color: "#FFFFFF",
        fontSize: 18,
        fontWeight: "900",
    },
    statusText: {
        width: "100%",
        maxWidth: 360,
        color: "#9AA4B8",
        fontSize: 14,
        textAlign: "center",
        marginBottom: 18,
    },
    board: {
        width: "100%",
        maxWidth: 360,
        aspectRatio: 1,
        flexDirection: "row",
        flexWrap: "wrap",
        borderRadius: 22,
        overflow: "hidden",
        backgroundColor: "#11182A",
        borderWidth: 1,
        borderColor: "#253046",
    },
    cell: {
        width: "33.3333%",
        height: "33.3333%",
        borderWidth: 0.5,
        borderColor: "#253046",
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: "#151C2E",
    },
    winningCell: {
        backgroundColor: "#20311F",
        borderColor: "#49D17D",
    },
    cellText: {
        fontSize: 48,
        fontWeight: "900",
    },
    xMark: {
        color: "#FFB74D",
    },
    oMark: {
        color: "#49D17D",
    },
    primaryButton: {
        width: "100%",
        maxWidth: 360,
        backgroundColor: "#FFB74D",
        borderRadius: 14,
        paddingVertical: 14,
        alignItems: "center",
        marginTop: 18,
    },
    primaryButtonText: {
        color: "#2A1600",
        fontSize: 12,
        fontWeight: "900",
        letterSpacing: 1,
    },
    resultHero: {
        width: "100%",
        maxWidth: 360,
        alignItems: "center",
        marginTop: 18,
        marginBottom: 14,
    },
    resultEmoji: {
        fontSize: 46,
        marginBottom: 8,
    },
    resultTitle: {
        color: "#FFFFFF",
        fontSize: 28,
        fontWeight: "900",
        textAlign: "center",
    },
    resultSubtitle: {
        color: "#9AA4B8",
        fontSize: 14,
        marginTop: 6,
        textAlign: "center",
        lineHeight: 20,
    },
    resultCard: {
        width: "100%",
        maxWidth: 360,
        backgroundColor: "#151C2E",
        borderWidth: 1,
        borderColor: "#253046",
        borderRadius: 18,
        padding: 16,
    },
    resultCardLabel: {
        color: "#8E99B0",
        fontSize: 11,
        fontWeight: "900",
        letterSpacing: 1,
        marginBottom: 12,
    },
});